### ISSUE TITLE
OS/2

### ISSUE THREAD

**Issue by TeLLie** [TweeChalice/TweeEditor#14]
Hello 
I compiled it in debug mode
It compiled without any error
But When i started the prog i see:
D:\Test\TweeEditor\resource>TweeEdit.exe
Installed font:  0
Creating 1168_01.TRP

i have a dir named resource with the font in it
How should the program find the font ?

**Comment by TweeChalice** [comment]
What's your version of Qt?
In my platform, it can detect the font. But it doesn't matter if it can't find the font. We will check this bug as well.

**Comment by TeLLie** [comment]
Hello

I use Qt v5.13.1and gcc 9.2.0

Op wo 27 mei 2020 04:03 schreef TweeChalice <notifications@github.com>:

**Comment by TweeChalice** [comment]
If the installed font outputs with `0`, it means the font has been installed in this application successfully and this number is the ID of the installed font.
If it outputs with `-1`, it meanse an error has been occured.

So, it outputs with `0`, there's no error. I have already tested it in Windows 10, it can detect the font.
The font will display in this application. You can see the displaying of TweeEditor.

I will close this issue now. If it can't display, you can create a new issue. 
Thank you for your support.
