### ISSUE TITLE
提两个建议

### ISSUE THREAD

**Issue by Linhk1606** [TweeChalice/TweeEditor#4]
1. 提示未保存(CloseEvent)时多一个cancel选项, 不然别人发现自己误点了关闭都没法回来保存
2. 打开font对话框时, 自动定位到原先选的那个字体

加上这两个可能会使应用更加人性化

**Comment by TweeChalice** [comment]
I will do it tonight.

**Comment by Linhk1606** [comment]
第一个我已解决

**Comment by TweeChalice** [comment]
solved
