### ISSUE TITLE
polish translation

### ISSUE THREAD

**Issue by nycko123** [TweeChalice/TweeEditor#5]
There is polish translation of TweeEditor created by Polish Arch Linux Community based on 1.0.3-pre1. Please feel free to add it to your code. .ts and .qm included
[TweeSimpleEdit_pl_PL.tar.gz](https://github.com/TweeChalice/TweeEditor/files/4267207/TweeSimpleEdit_pl_PL.tar.gz)

**Comment by Linhk1606** [comment]
Thanks for your support. We will do it soon.

**Comment by TweeChalice** [comment]
Thank you for supporting us! We have already added your translation.
