### ISSUE TITLE
tweefirstusedialog - master doesn't compile anymore

### ISSUE THREAD

**Issue by nycko123** [TweeChalice/TweeEditor#6]
Master branch does't compile anymore because of non-capitalized filenames:
=> tweefirstusedialog.{h.cpp}
which should be
=> TweeFirstUseDialog.{h,cpp}
or could be fixed other more proper way in the code itself.

Good starting project, keep it up guys!

**Comment by TweeChalice** [comment]
Thank you for your advice. I will change it soon.

**Comment by Linhk1606** [comment]
Fixed by @TweeChalice
