### ISSUE TITLE
1.0.4 failed to build

### ISSUE THREAD

**Issue by nycko123** [TweeChalice/TweeEditor#7]
There is physically no file 'ico/encoding.jpg' in the tree which is declared both in resource.qrc and Makefile.

**Comment by pavbaranov** [comment]
Exactly:

> make: *** No rule to make target 'ico/encoding.jpg', needed by 'qrc_resource.cpp'.  Stop.
==> ERROR: A failure occurred in build().<

**Comment by TweeChalice** [comment]
I will check it later. Thanks.

**Comment by TweeChalice** [comment]
I have already updated this project. Please check again whether it can build properly or not.

**Comment by pavbaranov** [comment]
I still cannot build v1.0.4. The same issue. But I can build v1.0.5pre2.

**Comment by TweeChalice** [comment]
Now the stable version is v.1.0.5, please use v. 1.0.5 because I have forgotten to upload the file in that history version. I will ask my partner to change the release as well.

**Comment by TweeChalice** [comment]
Please check if v.1.0.4 can build. Thank you for your support.

**Comment by TweeChalice** [comment]
I am sorry that there is something wrong with the version. Please wait for a few days, We will fix the problem.

**Comment by TweeChalice** [comment]
We have changed the version information.
Please check it again. (we haven't finish the encoding options completely, but we will finish it soon)
Thank you!

**Comment by TweeChalice** [comment]
The preview version: v1.0.4 Preview
The stable versionb v1.0.3

**Comment by pavbaranov** [comment]
Ok. So, I can build current version v1.0.4 Preview, but it doesn't works at all. It's another bug, I think so.

**Comment by TweeChalice** [comment]
Sorry, we haven't finish it yet. I just want to check whether it can build or not. We will update it later.
