### ISSUE TITLE
v1.0.4pre cannot be executed on Qt5.15beta1

### ISSUE THREAD

**Issue by pavbaranov** [TweeChalice/TweeEditor#8]
Current (today) version of v1.0.4. Preview can be build, but it doesn't works of all. 
I've built them:
- using cmake,
- against of Qt5.15beta1
System: Arch Linux (kde-unstable and testing/testing-community enabled and some changes to Plasma; KF5.67rc1, but KDE frameworks are irrelevant to TweeEditor).
Later I ask nycko123 to build it against of Qt5.14.1.
There's an output of gdb (TweeEditor build with Debug flag):

> Starting program: /usr/bin/tweeeditor 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff2f3c700 (LWP 21057)]
[New Thread 0x7fffebd4e700 (LWP 21062)]
ASSERT failure in QVector<T>::operator[]: "index out of range", file /usr/include/qt/QtCore/qvector.h, line 463

Thread 1 "tweeeditor" received signal SIGABRT, Aborted.
0x00007ffff68dfce5 in raise () from /usr/lib/libc.so.6

**Comment by nycko123** [comment]
I've just compiled v1.0.4pre against QT5.14.1 with no errors. Binary executes with no errors neither, so this version builds and works good.

**Comment by TweeChalice** [comment]
We will check it this week. Thank you very much.

**Comment by pavbaranov** [comment]
So, it seems like it's something with binary building against Qt5.15. 
The same issue occours with v1.0.5pre2 (I have this tarball) and doesn't occours with v1.0.3.
I built v1.0.4pre with qmake, too - the same error occours.

**Comment by TweeChalice** [comment]
Yes. I test it in Windows10, Qt 5.14.1, mingw64 with JetBrains Clion 2020.3, it runs as I hope
 it would.

**Comment by TweeChalice** [comment]
I wish to know more information about this problem.
Does it quit after or before showing the window ? 

If it quits after showing, we'd like to know what do you do and then it doesn't quit properly ?

**Comment by pavbaranov** [comment]
Any window is displaying. Start from konsole exit with: "Segmentation fault (core dumped)".
Probably it's related to new part of code introduced in 1.0.4pre and exists in 1.0.5pre2.

**Comment by TweeChalice** [comment]
You can try to delete 

>  document.resize(1)

> document.clearAll()

in the member function MainWindow::createTextEdit in mainwindow_oncreate.cpp.
Then build it again and see if it can display properly.
If it still not, please write down the bug here.

The version v1.0.4pre can build correctly in my platform, I don't know clearly how it is caused.

Thank you!

**Comment by pavbaranov** [comment]
There's not

> document.clearAll()
code in mainwindow_oncreate.cpp in version v1.0.4pre. We have there:
>void MainWindow::createTextEdit() {
    // sets up
    tabWidget = new QTabWidget;

    document.resize(1);
    document.clear();

I try to delete 
>  document.resize(1);
    document.clear();
Application builds well, but it cannot be execute at all:
> Starting program: /home/pavbaranov/Build/tweeeditor/src/TweeEditor-1.0.4pre/TweeEdit 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff2c56700 (LWP 69755)]
[New Thread 0x7fffeb97e700 (LWP 69756)]

Thread 1 "TweeEdit" received signal SIGSEGV, Segmentation fault.
0x000055555556304f in MainWindow::setTextEncoding(QString const&) ()

and of course any windows. 
 
Since the "new" version v1.0.4pre I have not any issue with building this application, only with execute it.

**Comment by TweeChalice** [comment]
Theoretically, I haven't checked out any problems with this code in this version.  I can use and run normally on my platform without throwing any errors. Maybe Qt beta itself may have some minor problems or it is not stable enough. I don’t know specifically because I use Qt stable version.
I am really sorry about that. You can try to build with Qt stable version.
I have tested this version since last week. If this problem still exists, I will test it again this weekend.

**Comment by TweeChalice** [comment]
If I find out the problem, we will update v.1.0.4pre this week. We need further verification. My partner and I are going to test it again.
Thank you so much for supporting us.

**Comment by pavbaranov** [comment]
As nycko123 said: it's not problem with your application build against Qt5.14.1. It works. I accept and respect that. There's no question with that at all. Please, consider, that my notification is only related with Qt 5.15 which is expected just round the corner at the middle of May 2020. Of course I'm only one from tester of it, and please understand that it's only notification about future Qt5 version and problem that exists with your application with it. Today, on stable version of Qt5 there's no problem. But... Qt5.15beta1 is stable enough. I use it for a while. It's very strange, that tweeeditor v1.0.3 works well build and execute on Qt5.15b1, but v.1.0.4 cannot be execute. It looks like the problem is in code of tweeeditor not in Qt5.15. I'm not a programmer, so I cannot help you more, than only notice a "bug". It's your decision that you can find a bug in your code, or you can announce this bug as a upstream bug in Qt5.

**Comment by TweeChalice** [comment]
I am really really sorry about that.
We are not programmers, either. We are students who interested in Qt and love cpp programming.
We are not able to check out the problem so far. I am sorry that we can not solve this problem now. We will wait for the new version of Qt and do some suitable changes. Sorry.

**Comment by TweeChalice** [comment]
So I have to add the 'wontfix' label to this issue temporarily till the new version comes out.

**Comment by TweeChalice** [comment]
But we will still try our best to find out the error. Thank you very much for helping us!

**Comment by pavbaranov** [comment]
Hmm... Stop apolagize each other. So now, with Qt5.14 there's no problem at all. But with 5.15 it'll may or not. If there is something that could help you to recognize problem - just ask me. I think that every information will be suitable. I think that there's someting wrong with this:

>  failure in QVector::operator[]: "index out of range", file /usr/include/qt/QtCore/qvector.h, line 463
and this not occours 1.0.3. So maybe we can recognize this problem inspect what's change in this line of code.

**Comment by TweeChalice** [comment]
Most likely now is we added some information about QVector operations on creating in the member function MainWindow:: getCurrentText in mainwindow_basic.cpp except MainWindow::createTextEdit, you.may try to 
delete

> if(currentText>=0)

And the following code block.

**Comment by TweeChalice** [comment]
I have changed a little code in v.1.0.4pre, you can try to build it. Thanks.

**Comment by pavbaranov** [comment]
Unfortunatelly the last build from v1.0.4pre give the same error. I cannot execute it at all. GDB report (build with -DCMAKE_BUILD_TYPE=Debug, but it looks like there's no debuging symbol in tweeeditor):

> Reading symbols from tweeeditor...
(No debugging symbols found in tweeeditor)
(gdb) r
Starting program: /usr/bin/tweeeditor 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff2c57700 (LWP 12739)]
[New Thread 0x7fffeb97f700 (LWP 12740)]
ASSERT failure in QVector<T>::operator[]: "index out of range", file /usr/include/qt/QtCore/qvector.h, line 463
Thread 1 "tweeeditor" received signal SIGABRT, Aborted.
0x00007ffff68dfce5 in raise () from /usr/lib/libc.so.6

**Comment by pavbaranov** [comment]
There's something strange with some informations. I've try to build with changes show there: https://github.com/TweeChalice/TweeEditor/issues/8#issuecomment-597929971 but there's no such line in the source code of v1.0.4 from: https://github.com/TweeChalice/TweeEditor/archive/v1.0.4pre.tar.gz
Even there: https://github.com/TweeChalice/TweeEditor/blob/v1.0.4pre/mainwindow_basic.cpp there's no "if(currentText)>0"...

**Comment by TweeChalice** [comment]
The code in preview version has changed little. 
**Now we are facing two situations here if the new preview version still fail to build, I need your information from building.**

Situation one:   You can see the other output of the terminal, like 'Selected language: ...' , ' currentText: ...'  and something just like these (except the throwing error of out of range')

Situation two: The displaying of the terminal is just the given output you have gave me

If this is 'Situation one', try to delete if(totalText) and the following block.
If this is 'Situation two', please let me know.

**Comment by pavbaranov** [comment]
I haven't got any problem with **building** (compile) tweeeditor v1.0.4, only with executing binary after compiling.
I've build from tarball from "archive" (this commit: https://github.com/TweeChalice/TweeEditor/commit/3521792a41ed8aad5bc71b809c952655f4c1d34c) and everything I wrote today is about this build.
I've just build from git tag=v1.0.4 and this bug still occours.
Only info that this apps gave me is:
1. When execute it from command line:

> $ tweeeditor
ASSERT failure in QVector<T>::operator[]: "index out of range", file /usr/include/qt/QtCore/qvector.h, line 463
Aborted (core dumped)

There's no problem with this line of QtCore with v1.0.3. Only for later version (1.0.4pre, 1.0.5pre2 or build from git master). The output is the dame. This is full and only output tweeeditor gave me when is executed from command line.
2. Output from GDB is always the same for any version above 1.0.3 (1.0.4pre, 1.0.5pre2, "master git") and it's:

> Starting program: /usr/bin/tweeeditor 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff2f3d700 (LWP 27735)]
[New Thread 0x7fffebd4e700 (LWP 27736)]
ASSERT failure in QVector<T>::operator[]: "index out of range", file /usr/include/qt/QtCore/qvector.h, line 463
Thread 1 "tweeeditor" received signal SIGABRT, Aborted.
0x00007ffff68dfce5 in raise () from /usr/lib/libc.so.6

So - for me - there's something new in yours code in version above 1.0.3 which isn't compatible with qt5-base (qt5 core) 5.15b1, and this is something related with QVector and not compatible with line 463 of qvector.h. This line is (/usr/include/qt/QtCore/qvector.h):

> { Q_ASSERT_X(i >= 0 && i < d->size, "QVector<T>::operator[]", "index out of range");
  return data()[i]; }
template <typename T>
inline void QVector<T>::insert(int i, const T &t)

**Comment by TweeChalice** [comment]
For this situation, I am afraid that I could do nothing to solve this problem. In my Qt stable version, it builds and runs correctly and there is no warnings and errors at all. According to the operation of vector, our changes doesn't influence the application. I think it is caused because of the changes of the Qvector in new version if Qt. But I know nothing about the beta version. I am afraid that I have to wait until the new version comes out and do a bit of change at that time.

**Comment by TweeChalice** [comment]
I debug it for many times, but am not able to find out any errors. The changes in the code don't influence the application as far as I know. We have used this application for several times, but there is no error found.

**Comment by pavbaranov** [comment]
Tomorrow should be Qt5.15b2 - let's see.

**Comment by pavbaranov** [comment]
Hmmm.... maybe... I know, that 5.15 wil be in some platform and distros at least in 2 months, but if you'd like to check what is wrong with qt5.15 or your application, the easiest way (I think) is to install Arch (or stricly-based Arch distro) on virtual machine. I can recomend i.e. Anarchy Linux or EndeavourOS. After installing remove "#" from /etc/pacman.conf before testing/community-testing and add:

> [kde-unstable]
Include = /etc/pacman.d/mirrorlist
After that - execute: sudo pacman -Syu

**Comment by TweeChalice** [comment]
Now I haven't checked out how it was caused. It seems that this bug will be solved when the new version of Qt comes out. But I suggest that you can also try to delete the contents of the member function MainWindow::createTextEdit temperarily.
But if the problem still exists, I am afraid that we have to wait until the new version.

**Comment by pavbaranov** [comment]
Why this bug is closed? There's any solutions...

**Comment by TweeChalice** [comment]
But I am sorry that this bug we won't solve it because we are in different version and in our version, there is no bug at all. 
I am sorry that we will close this bug **temporarily**  until we are in the same version and this bug is caused.

**Comment by TweeChalice** [comment]
Well, I reopened this issue, but we won't solve it recently.

**Comment by TweeChalice** [comment]
We fixed the error of `QVector` and it will be sent to Github soon.

**Comment by TweeChalice** [comment]
I have already canceled using QVector. It will no longer display the error. Thank you for your support.
