### ISSUE TITLE
v1.0.4pre doesn't remember user language choice

### ISSUE THREAD

**Issue by nycko123** [TweeChalice/TweeEditor#9]
Despite of having the specific language chosen (other then english - chinese or polish from dropdown menu), program still restarts using english.
`Selected language:  "简体中文"`
`Selected language:  "Polski"`

Runs with:
`Selected language:  ""`

**Comment by TweeChalice** [comment]
Thank you. We will do it this week.

**Comment by TweeChalice** [comment]
Thank you!
The bug has been solved in new version *v1.0.4pre*, you can download the code now.
If you have found out any problems, you can add a new issue.
